/**
 * gevLocalVoice.js — voice control against a local STT -> LLM -> TTS pipeline.
 *
 * A sibling transport to GevRealtimeController, not a replacement. That class
 * speaks OpenAI's Realtime protocol over WebRTC; this one drives three plain
 * HTTP endpoints proxied same-origin by localVoiceProxy():
 *
 *   mic -> VAD -> /api/voice/stt -> /api/voice/chat -> runGevAction()
 *              -> spoken confirmation -> /api/voice/tts -> playback
 *
 * The tool layer is shared verbatim: both transports call the same
 * createGevActionRunner(), so a tool behaves identically whichever mic is live.
 *
 * Two deliberate differences from the Realtime path:
 *
 *   1. Confirmations are TEMPLATED from tool results, not generated by a second
 *      model turn. That halves turn latency and removes the failure mode where a
 *      local model narrates success for a tool that actually failed.
 *   2. Audio is captured as raw 16 kHz PCM rather than MediaRecorder's WebM/Opus,
 *      because the STT service decodes WAV with soundfile and has no ffmpeg.
 */

import { createGevActionRunner } from './gevActions.js';

const STT_URL = '/api/voice/stt';
const CHAT_URL = '/api/voice/chat';
const TTS_URL = '/api/voice/tts';
const STATUS_URL = '/api/voice/status';

/** parakeet's native rate. Capturing here avoids a resample server-side. */
export const CAPTURE_SAMPLE_RATE = 16000;
/**
 * Absolute floor for the speech gate.
 *
 * A fixed threshold is fragile: getUserMedia's noiseSuppression and
 * echoCancellation both pull levels down, and headset vs. laptop mics differ by
 * an order of magnitude. So this is only the lower bound -- the live gate is
 * derived from the measured noise floor, see speechThreshold().
 */
export const SPEECH_FLOOR_MIN = 0.004;
/** Speech must exceed the noise floor by this factor to open the gate. */
export const SPEECH_FLOOR_MULTIPLIER = 3.5;
/** Seed noise floor before any audio has been observed. */
export const NOISE_FLOOR_SEED = 0.002;
/** How fast the noise-floor estimate tracks the room. */
export const NOISE_FLOOR_ALPHA = 0.05;

/**
 * Gate level for a given noise floor.
 *
 * @param {number} noiseFloor
 * @returns {number}
 */
export function speechThreshold(noiseFloor) {
  return Math.max(SPEECH_FLOOR_MIN, noiseFloor * SPEECH_FLOOR_MULTIPLIER);
}
/** Silence that ends an utterance. Long enough to survive a mid-sentence pause. */
export const SILENCE_HOLD_MS = 900;
/** Ignore blips shorter than this — a cough or a key click is not a command. */
export const MIN_UTTERANCE_MS = 350;
/** Hard stop so a stuck-open mic cannot upload unbounded audio. */
export const MAX_UTTERANCE_MS = 15000;

/**
 * Character budget for retained conversation.
 *
 * Follow-ups like "identify a bridge there" only work if the model can see the
 * previous turn, so history is kept -- but a voice session is long-lived and
 * tool results are verbose, so it is bounded rather than unbounded.
 */
export const MAX_HISTORY_CHARS = 6000;
/** Tool results are summaries for the model, not transcripts. */
export const MAX_TOOL_RESULT_CHARS = 800;

/**
 * Drop whole exchanges from the front until the history fits the budget.
 *
 * Trims only to a `user` boundary: a `tool` message orphaned from its
 * `assistant` tool_calls is a protocol error on most servers, so half an
 * exchange must never be left at the head.
 *
 * @param {Array<object>} history
 * @param {number} budget
 * @returns {Array<object>} the same array, trimmed in place
 */
export function trimHistory(history, budget = MAX_HISTORY_CHARS) {
  const size = () => history.reduce(
    (total, message) => total + String(message.content || '').length
      + (message.tool_calls ? JSON.stringify(message.tool_calls).length : 0),
    0,
  );
  while (history.length > 1 && size() > budget) {
    history.shift();
    while (history.length && history[0].role !== 'user') history.shift();
  }
  return history;
}

const STATUS_TEXT = {
  idle: 'OFF',
  listening: 'LISTENING',
  thinking: 'THINKING',
  executing: 'EXECUTING',
  speaking: 'SPEAKING',
  error: 'ERROR',
};

/**
 * Is the local voice pipeline configured on the server?
 *
 * @param {typeof fetch} [fetchImpl]
 * @returns {Promise<{enabled: boolean, model: string|null}>}
 */
export async function readLocalVoiceStatus(fetchImpl = fetch) {
  try {
    const response = await fetchImpl(STATUS_URL);
    if (!response.ok) return { enabled: false, model: null };
    const data = await response.json();
    return { enabled: Boolean(data?.enabled), model: data?.model ?? null };
  } catch {
    return { enabled: false, model: null };
  }
}

/**
 * Mean absolute amplitude of a frame. Cheaper than true RMS and adequate for
 * separating speech from room tone.
 *
 * @param {Float32Array} frame
 * @returns {number}
 */
export function frameLoudness(frame) {
  if (!frame || frame.length === 0) return 0;
  let total = 0;
  for (let i = 0; i < frame.length; i += 1) total += Math.abs(frame[i]);
  return total / frame.length;
}

/**
 * Encode mono float samples as a 16-bit PCM WAV.
 *
 * @param {Float32Array} samples
 * @param {number} sampleRate
 * @returns {Blob}
 */
export function encodeWav(samples, sampleRate = CAPTURE_SAMPLE_RATE) {
  const buffer = new ArrayBuffer(44 + samples.length * 2);
  const view = new DataView(buffer);
  const writeText = (offset, text) => {
    for (let i = 0; i < text.length; i += 1) view.setUint8(offset + i, text.charCodeAt(i));
  };
  writeText(0, 'RIFF');
  view.setUint32(4, 36 + samples.length * 2, true);
  writeText(8, 'WAVE');
  writeText(12, 'fmt ');
  view.setUint32(16, 16, true);
  view.setUint16(20, 1, true); // PCM
  view.setUint16(22, 1, true); // mono
  view.setUint32(24, sampleRate, true);
  view.setUint32(28, sampleRate * 2, true); // byte rate
  view.setUint16(32, 2, true); // block align
  view.setUint16(34, 16, true); // bits per sample
  writeText(36, 'data');
  view.setUint32(40, samples.length * 2, true);
  let offset = 44;
  for (let i = 0; i < samples.length; i += 1) {
    const clamped = Math.max(-1, Math.min(1, samples[i]));
    view.setInt16(offset, clamped < 0 ? clamped * 0x8000 : clamped * 0x7fff, true);
    offset += 2;
  }
  return new Blob([buffer], { type: 'audio/wav' });
}

/**
 * Turn executed tool results into one short spoken line.
 *
 * Deliberately templated rather than model-generated: the result objects already
 * say what happened, and a second model turn would both cost a round trip and
 * give a small model room to claim a success that did not occur.
 *
 * @param {Array<{name: string, result: object|null, error: string|null}>} outcomes
 * @returns {string}
 */
export function describeOutcomes(outcomes) {
  if (!outcomes.length) return '';
  const spoken = [];
  for (const { name, result, error } of outcomes) {
    if (error) {
      spoken.push(`${humanizeToolName(name)} failed`);
      continue;
    }
    if (result && result.ok === false) {
      spoken.push(result.error ? String(result.error) : `${humanizeToolName(name)} did not apply`);
      continue;
    }
    spoken.push(humanizeToolName(name));
  }
  const line = spoken.join(', ');
  return line.charAt(0).toUpperCase() + line.slice(1);
}

/** `set_layer_visibility` -> `set layer visibility`. */
function humanizeToolName(name) {
  return String(name || 'action').replace(/_/g, ' ');
}

/**
 * Parse tool calls out of a chat-completions response.
 *
 * @param {object} data
 * @returns {{calls: Array<{name: string, args: object}>, text: string, truncated: boolean}}
 */
export function parseChatToolCalls(data) {
  const choice = data?.choices?.[0] ?? {};
  const calls = (choice.message?.tool_calls ?? []).map((call, index) => {
    let args = {};
    try { args = JSON.parse(call.function?.arguments || '{}'); } catch { args = {}; }
    // The id is how a tool result is matched back to its call. Servers that omit
    // it still need a stable handle, so synthesize one.
    return { id: call.id || `call_${index}`, name: call.function?.name, args, raw: call };
  }).filter((call) => call.name);
  return {
    calls,
    text: String(choice.message?.content || '').trim(),
    truncated: choice.finish_reason === 'length',
  };
}

export class GevLocalVoiceController {
  constructor({ runner, ui, model = null }) {
    this.runner = runner;
    this.ui = ui;
    this.model = model;
    this.active = false;
    this.stream = null;
    this.audioContext = null;
    this.workletNode = null;
    this.sourceNode = null;
    this.player = null;
    /** @type {Float32Array[]} frames of the utterance currently being captured */
    this.captured = [];
    this.speaking = false;
    this.silenceMs = 0;
    this.utteranceMs = 0;
    /** Latched while a turn is in flight so speech during playback is ignored. */
    this.busy = false;
    /** Running estimate of room tone, used to derive the speech gate. */
    this.noiseFloor = NOISE_FLOOR_SEED;
    /** Conversation so far, so follow-ups such as "there" can resolve. */
    this.history = [];
    /** Diagnostics, surfaced through window.__gevVoiceDebug(). */
    this.stats = { frames: 0, peak: 0, lastLoudness: 0, utterances: 0, sampleRate: null };
    this.lastMeterAt = 0;
  }

  /** Start a fresh conversation without restarting the microphone. */
  resetConversation() {
    this.history = [];
  }

  /** Live capture diagnostics — the first thing to check when nothing happens. */
  debug() {
    return {
      active: this.active,
      busy: this.busy,
      speaking: this.speaking,
      framesSeen: this.stats.frames,
      sampleRate: this.stats.sampleRate,
      lastLoudness: Number(this.stats.lastLoudness.toFixed(5)),
      peakLoudness: Number(this.stats.peak.toFixed(5)),
      noiseFloor: Number(this.noiseFloor.toFixed(5)),
      speechThreshold: Number(speechThreshold(this.noiseFloor).toFixed(5)),
      utterancesSent: this.stats.utterances,
      historyMessages: this.history.length,
    };
  }

  isActive() {
    return this.active;
  }

  setStatus(key, detail = '') {
    if (this.ui?.root) this.ui.root.dataset.status = key;
    if (this.ui?.status) this.ui.status.textContent = STATUS_TEXT[key] || key.toUpperCase();
    if (this.ui?.detail) this.ui.detail.textContent = detail;
  }

  setError(message) {
    this.setStatus('error');
    if (this.ui?.errorDetail) this.ui.errorDetail.textContent = message;
  }

  /** Throttled input-level readout, so a silent mic is visible rather than guessed at. */
  showMeter(loudness) {
    const now = Date.now();
    if (now - this.lastMeterAt < 120) return;
    this.lastMeterAt = now;
    const gate = speechThreshold(this.noiseFloor);
    const bars = Math.min(10, Math.round((loudness / Math.max(gate, 1e-6)) * 5));
    this.setStatus('listening', `${'\u2588'.repeat(bars).padEnd(10, '\u00b7')} speak to command`);
  }

  async start() {
    if (this.active) return;
    if (!window.isSecureContext) {
      // getUserMedia is gated on a secure context. A LAN IP or a .local
      // hostname fails here with the same NotAllowedError as a real denial,
      // so name it separately -- the fix is completely different.
      this.setError(
        `Microphone needs a secure context. Open this over https, http://localhost, `
        + `or http://127.0.0.1 — not ${window.location.origin}.`,
      );
      return;
    }
    if (!navigator.mediaDevices?.getUserMedia || !window.AudioContext) {
      this.setError('This browser cannot capture microphone audio.');
      return;
    }
    this.setStatus('listening', 'Starting microphone');
    try {
      this.stream = await navigator.mediaDevices.getUserMedia({
        audio: { channelCount: 1, echoCancellation: true, noiseSuppression: true },
      });
    } catch (error) {
      this.setError(describeMicError(error));
      return;
    }

    try {
      // Ask for the model's rate directly; browsers that refuse it still work
      // because the service resamples, but this is the fast path.
      this.audioContext = new AudioContext({ sampleRate: CAPTURE_SAMPLE_RATE });
      await this.audioContext.audioWorklet.addModule(captureWorkletUrl());
      this.sourceNode = this.audioContext.createMediaStreamSource(this.stream);
      this.workletNode = new AudioWorkletNode(this.audioContext, 'gev-capture');
      this.workletNode.port.onmessage = (event) => this.onFrame(event.data);
      this.sourceNode.connect(this.workletNode);
      // A worklet with no downstream sink is not pulled in some browsers; a
      // zero-gain node keeps the graph alive without making sound.
      const mute = this.audioContext.createGain();
      mute.gain.value = 0;
      this.workletNode.connect(mute);
      mute.connect(this.audioContext.destination);
    } catch (error) {
      this.setError(`Audio pipeline failed: ${error?.message || error}`);
      this.stop();
      return;
    }

    this.stats.sampleRate = this.audioContext.sampleRate;
    if (this.audioContext.sampleRate !== CAPTURE_SAMPLE_RATE) {
      // Not fatal: the service resamples. Worth knowing while debugging though.
      console.info(`[gev-voice] capturing at ${this.audioContext.sampleRate} Hz`);
    }
    this.active = true;
    this.resetUtterance();
    this.setStatus('listening', this.model ? `Listening — ${this.model}` : 'Listening');
  }

  stop() {
    this.active = false;
    try { this.workletNode?.port && (this.workletNode.port.onmessage = null); } catch { /* ignore */ }
    try { this.sourceNode?.disconnect(); } catch { /* ignore */ }
    try { this.workletNode?.disconnect(); } catch { /* ignore */ }
    try { this.audioContext?.close(); } catch { /* ignore */ }
    for (const track of this.stream?.getTracks() ?? []) {
      try { track.stop(); } catch { /* ignore */ }
    }
    if (this.player) {
      try { this.player.pause(); } catch { /* ignore */ }
      this.player = null;
    }
    this.stream = null;
    this.audioContext = null;
    this.workletNode = null;
    this.sourceNode = null;
    this.resetUtterance();
    this.setStatus('idle');
  }

  resetUtterance() {
    this.captured = [];
    this.speaking = false;
    this.silenceMs = 0;
    this.utteranceMs = 0;
  }

  /**
   * Accumulate a frame and decide whether the utterance has ended.
   * @param {Float32Array} frame
   */
  onFrame(frame) {
    if (!this.active || this.busy || !frame?.length) return;
    // Use the context's ACTUAL rate: a browser may refuse the requested 16 kHz,
    // and timing computed from the wrong rate silently breaks the silence hold.
    const rate = this.audioContext?.sampleRate || CAPTURE_SAMPLE_RATE;
    const frameMs = (frame.length / rate) * 1000;
    const loudness = frameLoudness(frame);

    this.stats.frames += 1;
    this.stats.lastLoudness = loudness;
    if (loudness > this.stats.peak) this.stats.peak = loudness;

    const loud = loudness > speechThreshold(this.noiseFloor);
    if (!this.speaking) {
      // Track room tone only while nobody is talking, so speech cannot raise
      // the floor and gate itself out.
      this.noiseFloor += NOISE_FLOOR_ALPHA * (loudness - this.noiseFloor);
      this.showMeter(loudness);
      if (!loud) return;
      this.speaking = true;
    }

    this.captured.push(frame);
    this.utteranceMs += frameMs;
    this.silenceMs = loud ? 0 : this.silenceMs + frameMs;

    const ended = this.silenceMs >= SILENCE_HOLD_MS || this.utteranceMs >= MAX_UTTERANCE_MS;
    if (!ended) return;

    const frames = this.captured;
    const spokenMs = this.utteranceMs - this.silenceMs;
    this.resetUtterance();
    if (spokenMs < MIN_UTTERANCE_MS) return; // a click or a cough
    this.stats.utterances += 1;
    void this.runTurn(flattenFrames(frames), rate);
  }

  /**
   * One full turn: transcribe, route, execute, confirm.
   * @param {Float32Array} samples
   */
  async runTurn(samples, sampleRate = CAPTURE_SAMPLE_RATE) {
    this.busy = true;
    try {
      this.setStatus('thinking', 'Transcribing');
      // Label the WAV with the rate it was actually captured at. Mislabelling
      // here does not error -- it just transcribes as gibberish.
      const wav = encodeWav(samples, sampleRate);
      const sttResponse = await fetch(STT_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'audio/wav' },
        body: wav,
      });
      if (!sttResponse.ok) throw new Error(`STT failed (${sttResponse.status})`);
      const transcript = String((await sttResponse.json())?.text || '').trim();
      if (!transcript) {
        this.setStatus('listening', 'Nothing heard');
        return;
      }
      this.setStatus('thinking', transcript);

      this.history.push({ role: 'user', content: transcript });
      trimHistory(this.history);

      const chatResponse = await fetch(CHAT_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ messages: this.history }),
      });
      if (!chatResponse.ok) throw new Error(`Voice model failed (${chatResponse.status})`);
      const { calls, text, truncated } = parseChatToolCalls(await chatResponse.json());

      if (!calls.length) {
        // Conversational turn, or the model ran out of room mid-call. Either way
        // it is part of the conversation and belongs in the history.
        const reply = truncated ? 'Sorry, I lost that one.' : (text || 'I did not catch a command.');
        this.history.push({ role: 'assistant', content: reply });
        await this.speak(reply);
        return;
      }

      // Record the assistant turn BEFORE executing, so that a tool which throws
      // still leaves a well-formed call/response pair behind it.
      this.history.push({
        role: 'assistant',
        content: text || '',
        tool_calls: calls.map((call) => call.raw),
      });

      this.setStatus('executing', calls.map((c) => c.name).join(', '));
      const outcomes = [];
      for (const call of calls) {
        let payload;
        try {
          const result = await this.runner(call.name, call.args);
          outcomes.push({ name: call.name, result, error: null });
          payload = result;
        } catch (error) {
          const message = String(error?.message || error);
          outcomes.push({ name: call.name, result: null, error: message });
          payload = { ok: false, error: message };
        }
        // Feed the real outcome back. This is what lets "identify a bridge
        // there" resolve: the model can see it flew to Boston and what came of it.
        this.history.push({
          role: 'tool',
          tool_call_id: call.id,
          content: JSON.stringify(payload ?? null).slice(0, MAX_TOOL_RESULT_CHARS),
        });
      }
      trimHistory(this.history);
      await this.speak(describeOutcomes(outcomes));
    } catch (error) {
      this.setError(String(error?.message || error));
    } finally {
      this.busy = false;
      if (this.active) this.setStatus('listening', 'Listening');
    }
  }

  /**
   * Synthesize and play one line, resolving when playback finishes so the mic
   * does not transcribe our own output.
   *
   * @param {string} line
   */
  async speak(line) {
    const text = String(line || '').trim();
    if (!text) return;
    this.setStatus('speaking', text);
    let url = null;
    try {
      const response = await fetch(TTS_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ text }),
      });
      if (!response.ok) return; // a missed confirmation must not fail the turn
      url = URL.createObjectURL(await response.blob());
      const audio = new Audio(url);
      this.player = audio;
      await new Promise((resolve) => {
        audio.onended = resolve;
        audio.onerror = resolve;
        audio.play().catch(resolve);
      });
    } catch {
      // Playback is best-effort; the tools already ran.
    } finally {
      if (url) URL.revokeObjectURL(url);
      this.player = null;
    }
  }
}

/**
 * Turn a getUserMedia rejection into something the user can act on.
 *
 * The DOMException name is the only reliable signal, and the two common causes
 * of NotAllowedError -- a site permission the browser remembered, and a missing
 * OS-level grant for the browser itself -- need different fixes, so both are
 * named rather than guessed between.
 *
 * @param {unknown} error
 * @returns {string}
 */
export function describeMicError(error) {
  switch (error?.name) {
    case 'NotAllowedError':
      return 'Microphone blocked. Allow it for this site (padlock in the address bar), '
        + 'and check System Settings > Privacy & Security > Microphone for your browser.';
    case 'NotFoundError':
    case 'OverconstrainedError':
      return 'No microphone found. Connect one and try again.';
    case 'NotReadableError':
      return 'The microphone is in use by another app. Close it and try again.';
    case 'AbortError':
      return 'The microphone could not be started. Try again.';
    default:
      return `Microphone unavailable (${error?.name || 'unknown error'}).`;
  }
}

/** Concatenate captured frames into one contiguous buffer. */
function flattenFrames(frames) {
  const total = frames.reduce((sum, frame) => sum + frame.length, 0);
  const out = new Float32Array(total);
  let offset = 0;
  for (const frame of frames) {
    out.set(frame, offset);
    offset += frame.length;
  }
  return out;
}

let workletUrl = null;
/**
 * AudioWorklet that forwards mono frames to the main thread.
 *
 * Built from a Blob so the worklet ships with this module rather than as a
 * separate asset that Vite would have to be told to emit. ScriptProcessorNode
 * would be shorter but is deprecated and runs on the main thread.
 *
 * @returns {string} object URL for the worklet module
 */
function captureWorkletUrl() {
  if (workletUrl) return workletUrl;
  const source = `
    class GevCapture extends AudioWorkletProcessor {
      process(inputs) {
        const channel = inputs[0] && inputs[0][0];
        if (channel && channel.length) this.port.postMessage(new Float32Array(channel));
        return true;
      }
    }
    registerProcessor('gev-capture', GevCapture);
  `;
  workletUrl = URL.createObjectURL(new Blob([source], { type: 'application/javascript' }));
  return workletUrl;
}

/**
 * Wire the local voice controller to the shared GEV MIC surface.
 *
 * Mirrors initGevVoiceCommands so main.js can pick a transport without knowing
 * which one it got.
 *
 * @returns {GevLocalVoiceController}
 */
export function initGevLocalVoiceCommands({
  viewer, styleManager, dataManager, sceneDirector = null, annotations = null,
  ui, model = null,
}) {
  if (window.__gevVoiceCommands && typeof window.__gevVoiceCommands.stop === 'function') {
    window.__gevVoiceCommands.stop({ removeUi: true });
  }
  const runner = createGevActionRunner({ viewer, styleManager, dataManager, sceneDirector, annotations });
  const controller = new GevLocalVoiceController({ runner, ui, model });
  controller.buttonHandler = () => {
    if (controller.isActive()) controller.stop();
    else void controller.start();
  };
  ui.button.addEventListener('click', controller.buttonHandler);
  // Cost controls are meaningless locally; the model runs on your own hardware.
  if (ui.tierButton) ui.tierButton.style.display = 'none';
  if (ui.costValue) ui.costValue.textContent = 'local';
  window.__gevVoiceCommands = controller;
  // Capture diagnostics without opening devtools sources: __gevVoiceDebug()
  window.__gevVoiceDebug = () => controller.debug();
  return controller;
}
