/**
 * gevLocalVoice.js — voice control against a local STT -> LLM -> TTS pipeline.
 *
 * A sibling transport to GevRealtimeController, not a replacement. That class
 * speaks OpenAI's Realtime protocol over WebRTC; this one drives three plain
 * HTTP endpoints proxied same-origin by localVoiceProxy():
 *
 *   mic -> VAD -> /api/voice/stt -> /api/voice/chat -> runGevAction()
 *              -> spoken confirmation -> /api/voice/tts -> playback
 *
 * The tool layer is shared verbatim: both transports call the same
 * createGevActionRunner(), so a tool behaves identically whichever mic is live.
 *
 * Two deliberate differences from the Realtime path:
 *
 *   1. Confirmations are TEMPLATED from tool results, not generated by a second
 *      model turn. That halves turn latency and removes the failure mode where a
 *      local model narrates success for a tool that actually failed.
 *   2. Audio is captured as raw 16 kHz PCM rather than MediaRecorder's WebM/Opus,
 *      because the STT service decodes WAV with soundfile and has no ffmpeg.
 */

import { createGevActionRunner } from './gevActions.js';

const STT_URL = '/api/voice/stt';
const CHAT_URL = '/api/voice/chat';
const TTS_URL = '/api/voice/tts';
const STATUS_URL = '/api/voice/status';

/** parakeet's native rate. Capturing here avoids a resample server-side. */
export const CAPTURE_SAMPLE_RATE = 16000;
/** Mean absolute amplitude above which a frame counts as speech. */
export const SPEECH_RMS_THRESHOLD = 0.012;
/** Silence that ends an utterance. Long enough to survive a mid-sentence pause. */
export const SILENCE_HOLD_MS = 900;
/** Ignore blips shorter than this — a cough or a key click is not a command. */
export const MIN_UTTERANCE_MS = 350;
/** Hard stop so a stuck-open mic cannot upload unbounded audio. */
export const MAX_UTTERANCE_MS = 15000;

const STATUS_TEXT = {
  idle: 'OFF',
  listening: 'LISTENING',
  thinking: 'THINKING',
  executing: 'EXECUTING',
  speaking: 'SPEAKING',
  error: 'ERROR',
};

/**
 * Is the local voice pipeline configured on the server?
 *
 * @param {typeof fetch} [fetchImpl]
 * @returns {Promise<{enabled: boolean, model: string|null}>}
 */
export async function readLocalVoiceStatus(fetchImpl = fetch) {
  try {
    const response = await fetchImpl(STATUS_URL);
    if (!response.ok) return { enabled: false, model: null };
    const data = await response.json();
    return { enabled: Boolean(data?.enabled), model: data?.model ?? null };
  } catch {
    return { enabled: false, model: null };
  }
}

/**
 * Mean absolute amplitude of a frame. Cheaper than true RMS and adequate for
 * separating speech from room tone.
 *
 * @param {Float32Array} frame
 * @returns {number}
 */
export function frameLoudness(frame) {
  if (!frame || frame.length === 0) return 0;
  let total = 0;
  for (let i = 0; i < frame.length; i += 1) total += Math.abs(frame[i]);
  return total / frame.length;
}

/**
 * Encode mono float samples as a 16-bit PCM WAV.
 *
 * @param {Float32Array} samples
 * @param {number} sampleRate
 * @returns {Blob}
 */
export function encodeWav(samples, sampleRate = CAPTURE_SAMPLE_RATE) {
  const buffer = new ArrayBuffer(44 + samples.length * 2);
  const view = new DataView(buffer);
  const writeText = (offset, text) => {
    for (let i = 0; i < text.length; i += 1) view.setUint8(offset + i, text.charCodeAt(i));
  };
  writeText(0, 'RIFF');
  view.setUint32(4, 36 + samples.length * 2, true);
  writeText(8, 'WAVE');
  writeText(12, 'fmt ');
  view.setUint32(16, 16, true);
  view.setUint16(20, 1, true); // PCM
  view.setUint16(22, 1, true); // mono
  view.setUint32(24, sampleRate, true);
  view.setUint32(28, sampleRate * 2, true); // byte rate
  view.setUint16(32, 2, true); // block align
  view.setUint16(34, 16, true); // bits per sample
  writeText(36, 'data');
  view.setUint32(40, samples.length * 2, true);
  let offset = 44;
  for (let i = 0; i < samples.length; i += 1) {
    const clamped = Math.max(-1, Math.min(1, samples[i]));
    view.setInt16(offset, clamped < 0 ? clamped * 0x8000 : clamped * 0x7fff, true);
    offset += 2;
  }
  return new Blob([buffer], { type: 'audio/wav' });
}

/**
 * Turn executed tool results into one short spoken line.
 *
 * Deliberately templated rather than model-generated: the result objects already
 * say what happened, and a second model turn would both cost a round trip and
 * give a small model room to claim a success that did not occur.
 *
 * @param {Array<{name: string, result: object|null, error: string|null}>} outcomes
 * @returns {string}
 */
export function describeOutcomes(outcomes) {
  if (!outcomes.length) return '';
  const spoken = [];
  for (const { name, result, error } of outcomes) {
    if (error) {
      spoken.push(`${humanizeToolName(name)} failed`);
      continue;
    }
    if (result && result.ok === false) {
      spoken.push(result.error ? String(result.error) : `${humanizeToolName(name)} did not apply`);
      continue;
    }
    spoken.push(humanizeToolName(name));
  }
  const line = spoken.join(', ');
  return line.charAt(0).toUpperCase() + line.slice(1);
}

/** `set_layer_visibility` -> `set layer visibility`. */
function humanizeToolName(name) {
  return String(name || 'action').replace(/_/g, ' ');
}

/**
 * Parse tool calls out of a chat-completions response.
 *
 * @param {object} data
 * @returns {{calls: Array<{name: string, args: object}>, text: string, truncated: boolean}}
 */
export function parseChatToolCalls(data) {
  const choice = data?.choices?.[0] ?? {};
  const calls = (choice.message?.tool_calls ?? []).map((call) => {
    let args = {};
    try { args = JSON.parse(call.function?.arguments || '{}'); } catch { args = {}; }
    return { name: call.function?.name, args };
  }).filter((call) => call.name);
  return {
    calls,
    text: String(choice.message?.content || '').trim(),
    truncated: choice.finish_reason === 'length',
  };
}

export class GevLocalVoiceController {
  constructor({ runner, ui, model = null }) {
    this.runner = runner;
    this.ui = ui;
    this.model = model;
    this.active = false;
    this.stream = null;
    this.audioContext = null;
    this.workletNode = null;
    this.sourceNode = null;
    this.player = null;
    /** @type {Float32Array[]} frames of the utterance currently being captured */
    this.captured = [];
    this.speaking = false;
    this.silenceMs = 0;
    this.utteranceMs = 0;
    /** Latched while a turn is in flight so speech during playback is ignored. */
    this.busy = false;
  }

  isActive() {
    return this.active;
  }

  setStatus(key, detail = '') {
    if (this.ui?.root) this.ui.root.dataset.status = key;
    if (this.ui?.status) this.ui.status.textContent = STATUS_TEXT[key] || key.toUpperCase();
    if (this.ui?.detail) this.ui.detail.textContent = detail;
  }

  setError(message) {
    this.setStatus('error');
    if (this.ui?.errorDetail) this.ui.errorDetail.textContent = message;
  }

  async start() {
    if (this.active) return;
    if (!navigator.mediaDevices?.getUserMedia || !window.AudioContext) {
      this.setError('This browser cannot capture microphone audio.');
      return;
    }
    this.setStatus('listening', 'Starting microphone');
    try {
      this.stream = await navigator.mediaDevices.getUserMedia({
        audio: { channelCount: 1, echoCancellation: true, noiseSuppression: true },
      });
    } catch (error) {
      this.setError(`Microphone permission denied (${error?.name || 'error'}).`);
      return;
    }

    try {
      // Ask for the model's rate directly; browsers that refuse it still work
      // because the service resamples, but this is the fast path.
      this.audioContext = new AudioContext({ sampleRate: CAPTURE_SAMPLE_RATE });
      await this.audioContext.audioWorklet.addModule(captureWorkletUrl());
      this.sourceNode = this.audioContext.createMediaStreamSource(this.stream);
      this.workletNode = new AudioWorkletNode(this.audioContext, 'gev-capture');
      this.workletNode.port.onmessage = (event) => this.onFrame(event.data);
      this.sourceNode.connect(this.workletNode);
      // A worklet with no downstream sink is not pulled in some browsers; a
      // zero-gain node keeps the graph alive without making sound.
      const mute = this.audioContext.createGain();
      mute.gain.value = 0;
      this.workletNode.connect(mute);
      mute.connect(this.audioContext.destination);
    } catch (error) {
      this.setError(`Audio pipeline failed: ${error?.message || error}`);
      this.stop();
      return;
    }

    this.active = true;
    this.resetUtterance();
    this.setStatus('listening', this.model ? `Listening — ${this.model}` : 'Listening');
  }

  stop() {
    this.active = false;
    try { this.workletNode?.port && (this.workletNode.port.onmessage = null); } catch { /* ignore */ }
    try { this.sourceNode?.disconnect(); } catch { /* ignore */ }
    try { this.workletNode?.disconnect(); } catch { /* ignore */ }
    try { this.audioContext?.close(); } catch { /* ignore */ }
    for (const track of this.stream?.getTracks() ?? []) {
      try { track.stop(); } catch { /* ignore */ }
    }
    if (this.player) {
      try { this.player.pause(); } catch { /* ignore */ }
      this.player = null;
    }
    this.stream = null;
    this.audioContext = null;
    this.workletNode = null;
    this.sourceNode = null;
    this.resetUtterance();
    this.setStatus('idle');
  }

  resetUtterance() {
    this.captured = [];
    this.speaking = false;
    this.silenceMs = 0;
    this.utteranceMs = 0;
  }

  /**
   * Accumulate a frame and decide whether the utterance has ended.
   * @param {Float32Array} frame
   */
  onFrame(frame) {
    if (!this.active || this.busy || !frame?.length) return;
    const frameMs = (frame.length / CAPTURE_SAMPLE_RATE) * 1000;
    const loud = frameLoudness(frame) > SPEECH_RMS_THRESHOLD;

    if (!this.speaking) {
      if (!loud) return; // still waiting for speech to begin
      this.speaking = true;
    }

    this.captured.push(frame);
    this.utteranceMs += frameMs;
    this.silenceMs = loud ? 0 : this.silenceMs + frameMs;

    const ended = this.silenceMs >= SILENCE_HOLD_MS || this.utteranceMs >= MAX_UTTERANCE_MS;
    if (!ended) return;

    const frames = this.captured;
    const spokenMs = this.utteranceMs - this.silenceMs;
    this.resetUtterance();
    if (spokenMs < MIN_UTTERANCE_MS) return; // a click or a cough
    void this.runTurn(flattenFrames(frames));
  }

  /**
   * One full turn: transcribe, route, execute, confirm.
   * @param {Float32Array} samples
   */
  async runTurn(samples) {
    this.busy = true;
    try {
      this.setStatus('thinking', 'Transcribing');
      const wav = encodeWav(samples);
      const sttResponse = await fetch(STT_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'audio/wav' },
        body: wav,
      });
      if (!sttResponse.ok) throw new Error(`STT failed (${sttResponse.status})`);
      const transcript = String((await sttResponse.json())?.text || '').trim();
      if (!transcript) {
        this.setStatus('listening', 'Nothing heard');
        return;
      }
      this.setStatus('thinking', transcript);

      const chatResponse = await fetch(CHAT_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ messages: [{ role: 'user', content: transcript }] }),
      });
      if (!chatResponse.ok) throw new Error(`Voice model failed (${chatResponse.status})`);
      const { calls, text, truncated } = parseChatToolCalls(await chatResponse.json());

      if (!calls.length) {
        // Conversational turn, or the model ran out of room mid-call.
        await this.speak(truncated ? 'Sorry, I lost that one.' : (text || 'I did not catch a command.'));
        return;
      }

      this.setStatus('executing', calls.map((c) => c.name).join(', '));
      const outcomes = [];
      for (const call of calls) {
        try {
          const result = await this.runner(call.name, call.args);
          outcomes.push({ name: call.name, result, error: null });
        } catch (error) {
          outcomes.push({ name: call.name, result: null, error: String(error?.message || error) });
        }
      }
      await this.speak(describeOutcomes(outcomes));
    } catch (error) {
      this.setError(String(error?.message || error));
    } finally {
      this.busy = false;
      if (this.active) this.setStatus('listening', 'Listening');
    }
  }

  /**
   * Synthesize and play one line, resolving when playback finishes so the mic
   * does not transcribe our own output.
   *
   * @param {string} line
   */
  async speak(line) {
    const text = String(line || '').trim();
    if (!text) return;
    this.setStatus('speaking', text);
    let url = null;
    try {
      const response = await fetch(TTS_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ text }),
      });
      if (!response.ok) return; // a missed confirmation must not fail the turn
      url = URL.createObjectURL(await response.blob());
      const audio = new Audio(url);
      this.player = audio;
      await new Promise((resolve) => {
        audio.onended = resolve;
        audio.onerror = resolve;
        audio.play().catch(resolve);
      });
    } catch {
      // Playback is best-effort; the tools already ran.
    } finally {
      if (url) URL.revokeObjectURL(url);
      this.player = null;
    }
  }
}

/** Concatenate captured frames into one contiguous buffer. */
function flattenFrames(frames) {
  const total = frames.reduce((sum, frame) => sum + frame.length, 0);
  const out = new Float32Array(total);
  let offset = 0;
  for (const frame of frames) {
    out.set(frame, offset);
    offset += frame.length;
  }
  return out;
}

let workletUrl = null;
/**
 * AudioWorklet that forwards mono frames to the main thread.
 *
 * Built from a Blob so the worklet ships with this module rather than as a
 * separate asset that Vite would have to be told to emit. ScriptProcessorNode
 * would be shorter but is deprecated and runs on the main thread.
 *
 * @returns {string} object URL for the worklet module
 */
function captureWorkletUrl() {
  if (workletUrl) return workletUrl;
  const source = `
    class GevCapture extends AudioWorkletProcessor {
      process(inputs) {
        const channel = inputs[0] && inputs[0][0];
        if (channel && channel.length) this.port.postMessage(new Float32Array(channel));
        return true;
      }
    }
    registerProcessor('gev-capture', GevCapture);
  `;
  workletUrl = URL.createObjectURL(new Blob([source], { type: 'application/javascript' }));
  return workletUrl;
}

/**
 * Wire the local voice controller to the shared GEV MIC surface.
 *
 * Mirrors initGevVoiceCommands so main.js can pick a transport without knowing
 * which one it got.
 *
 * @returns {GevLocalVoiceController}
 */
export function initGevLocalVoiceCommands({
  viewer, styleManager, dataManager, sceneDirector = null, annotations = null,
  ui, model = null,
}) {
  if (window.__gevVoiceCommands && typeof window.__gevVoiceCommands.stop === 'function') {
    window.__gevVoiceCommands.stop({ removeUi: true });
  }
  const runner = createGevActionRunner({ viewer, styleManager, dataManager, sceneDirector, annotations });
  const controller = new GevLocalVoiceController({ runner, ui, model });
  controller.buttonHandler = () => {
    if (controller.isActive()) controller.stop();
    else void controller.start();
  };
  ui.button.addEventListener('click', controller.buttonHandler);
  // Cost controls are meaningless locally; the model runs on your own hardware.
  if (ui.tierButton) ui.tierButton.style.display = 'none';
  if (ui.costValue) ui.costValue.textContent = 'local';
  window.__gevVoiceCommands = controller;
  return controller;
}
